import { MenuItem, SiteSettings } from "./types";

export const INITIAL_MENU: MenuItem[] = [
  {
    id: "1",
    name: "Margherita Pizza",
    category: "Pizza",
    price: 799,
    rating: 4.7,
    description: "Classic tomato base, fresh mozzarella, basil leaves and a drizzle of olive oil.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&auto=format&fit=crop",
    badge: "Classic",
    isPopular: false,
  },
  {
    id: "2",
    name: "Pepperoni Feast",
    category: "Pizza",
    price: 1099,
    rating: 4.8,
    description: "Loaded with pepperoni, mozzarella, and our signature tomato sauce.",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500&auto=format&fit=crop",
    badge: "Popular",
    isPopular: true,
  },
  {
    id: "4",
    name: "Classic Cheeseburger",
    category: "Burger",
    price: 599,
    rating: 4.9,
    description: "Juicy beef patty, cheddar cheese, lettuce, tomato, and special sauce.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop",
    badge: "Bestseller",
    isPopular: true,
  },
  {
    id: "7",
    name: "Steamed Chicken Momo",
    category: "Momo",
    price: 399,
    rating: 4.8,
    description: "Hand-crafted dumplings filled with spiced chicken, served with tomato-sesame chutney.",
    image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&auto=format&fit=crop",
    badge: "Fan Fav",
    isPopular: true,
  },
  {
    id: "9",
    name: "Salmon Nigiri",
    category: "Sushi",
    price: 1299,
    rating: 4.9,
    description: "Fresh Atlantic salmon over seasoned Japanese rice, served with pickled ginger.",
    image: "https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=500&auto=format&fit=crop",
    badge: "Fresh",
    isPopular: true,
  },
  {
    id: "11",
    name: "Chocolate Lava Cake",
    category: "Dessert",
    price: 399,
    rating: 4.9,
    description: "Warm molten chocolate cake with vanilla bean ice cream and caramel drizzle.",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=500&auto=format&fit=crop",
    badge: "Sweet",
    isPopular: true,
  },
];

export const INITIAL_SETTINGS: SiteSettings = {
  siteName: "Delicious Bite",
  deliveryFee: 100,
  taxRate: 0.13,
  contactPhone: "+977 9800000000",
  contactEmail: "info@deliciousbite.com",
  contactAddress: "123 Food Street, Kathmandu, Nepal",
  currencySymbol: "रु",
};
